// <auto-generated />
using DESIGNBASE.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DESIGNBASE.Migrations
{
    [DbContext(typeof(DesignBaseContext))]
    [Migration("20211014131527_mig_1")]
    partial class mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DESIGNBASE.Entities.ProjeGenel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACIKALAMALAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BAGLANTI_GRUBU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CALISMA_YERI_SIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CALISMA_YERI_YUK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DENGELEME_SARGISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FREKANS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMALAT_NORMU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAX_KD_SURESI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJE_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SARGI_OLCULERI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SARGI_SAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SARGI_SIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SARIM_GERILIMI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIPARIS_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOGUTMA_SEKLI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOGUTMA_SEKLI1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOGUTMA_SEKLI2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOGUTMA_SEKLI3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TASARIM_BELGESI_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TASARIM_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TETA_MUH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOPLAM_BAKIR_AGIRLIGI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRAFO_TANIM_KODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YAG_SIC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ProjeGenel");
                });
#pragma warning restore 612, 618
        }
    }
}
